### ISSUE TITLE
声网Agora.io全球黑客松中国站收官，开源全球首个实时互动直播App－OpenLive

### ISSUE THREAD

**Issue by poholo** [AgoraLab/OpenLive_iOS#1]
声网Agora.io全球黑客松中国站收官，开源全球首个实时互动直播App－OpenLive

有开源吗 ？

**Comment by PRWrl** [comment]
这个库就是App开源，另外还有[OpenVideoCall](https://github.com/AgoraLab/OpenVideoCall_iOS)、[OpenVoiceCall](https://github.com/AgoraLab/OpenVoiceCall_iOS)
