### ISSUE TITLE
unable to build open live i think you must include workspace file

### ISSUE THREAD

**Issue by quickstreamingmedia** [AgoraLab/OpenLive_iOS#2]
http://prntscr.com/diobus

check and let me know

**Comment by jtbarker** [comment]
Replicated this as well.

**Comment by jamfang** [comment]
Please try Build Phases -> Link Binary with Libraries, and add libresolv.tbd

![image](https://cloud.githubusercontent.com/assets/17418615/26595291/c385238c-451f-11e7-90aa-7e9fd8a6ce5f.png)
